---
# tasks file for loadbalancer
  - name: installing the haproxy softawre
    package:
            name: "haproxy"
            state: present
    notify:
            start haproxy service

  - name: copy config file
    template:
            src: /etc/haproxy.cfg
            dest: /etc/haproxy/haproxy.cfg
    notify:
    - restart haproxy service

           
           
